### ISSUE TITLE
Fatal ERROR

### ISSUE THREAD

**Issue by einspyon** [rubengooj/pl-slam#10]
Hi ! 
 #error **FATAL ERROR**: MRPT headers must be included before Eigen headers
 What's the problem with this ???

**Comment by LinHuican** [comment]
@einspyon I have the same problem, do you solve it?

**Comment by einspyon** [comment]
I just install the MRPT1.5 library again according to : https://github.com/MRPT/mrpt/tree/mrpt-1.5
it will be ok
