### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by hitzhang** [rubengooj/pl-slam#32]
Initializing PL-SLAM....

(MRPT:13577): Gtk-ERROR **: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported
追踪与中断点陷阱

**Comment by BING-ZHANG** [comment]
同学，我也遇到了这个问题，请问你解决了吗？

**Comment by hitzhang** [comment]
> 同学，我也遇到了这个问题，请问你解决了吗？

重编opencv with gtk

**Comment by calmelo** [comment]
> > 同学，我也遇到了这个问题，请问你解决了吗？
> 
> 重编opencv with gtk

请问是用gtk3重编译还是gtk2重编译啊？我看MRPT要求安装的也是gtk3

**Comment by Pf123** [comment]
> 

请问编译PL-SLAM需要用哪个版本的MRPT呢？作者推荐的那个一直安装不上

**Comment by BTREE-C802** [comment]
您好，我叫旷鸿章，我已经收到了你的邮件。谢谢！

**Comment by Akira151** [comment]
选择gtk2.0选项重新编译opencv（在编译选项中的WITH_GTK_2_X和WITH_GTK全选成ON），成功运行了。非常感谢！
代码用的是pl-slam作者版本的，mrpt用的是mrpt作者在pl-slam中提交的pull request的readme中所给出的apt-get install版本的https://github.com/jlblancoc/pl-slam/tree/master，版本号是1.5。
搞了三天终于跑通了。。omg

**Comment by BTREE-C802** [comment]
您好，我叫旷鸿章，我已经收到了你的邮件。谢谢！
