### ISSUE TITLE
segmentation fault when running different EuRoc dataset

### ISSUE THREAD

**Issue by dengzhiwei12** [rubengooj/pl-slam#38]
When I run the EuRoc dataset MH_05_difficult and the MH_01_easy. There is a segmentation fault.
like this:
Initializing PL-SLAM.... ... done. 
------------------------------------------   Frame #1   ----------------------------------------

VO Runtime: 51.0406

No new KF needed: 1	-35.7409 -35.7409 3.63931e-39	0.0114124 0.167611 0

[1]    25583 segmentation fault  ./plslam_dataset mav0 -c ../config/config/config_euroc.yaml -o 100 -s 1

But when I run the MH_03_medium, there is no error. I don't know why this happened.
And when I run the MH_03_medium, I did't find any line features. Maybe because the image display window is too small so that I can't find it.
If someone know it, please let me know. Thanks

best

**Comment by dengzhiwei12** [comment]
I am sorry for that question. It's my datasets' error. It seems that my datasets missed a few images.
And I find some line segments, but it's really hard to find it. The image display window is really small.
Sorry for my questions, and thanks a lot for your source code!

best

**Comment by Yanjiqiang** [comment]
hi,I also encountered this problem, have you solved this problem? If so, how was it solved?
