### ISSUE TITLE
about g2o

### ISSUE THREAD

**Issue by Chrislzy1993** [rubengooj/pl-slam#5]
hey,i have  a issue like the follow:
Linking CXX shared library ../lib/libplslam.so
/usr/bin/ld: can not find -lg2o_ext_csparse
and i checked the floder of usr and cant find the libg2o_ext_csparse?
could u help me ?

**Comment by chaiein** [comment]
export LIBRARY_PATH=<path of g2o/lib/>  and run the code.

**Comment by xmupamizq** [comment]
@GeeKmyself I suggest you that 
cd /usr/local/lib
sudo ln -sv libg2o_csparse_extension.so libg2o_ext_csparse
that is all.

**Comment by SLAMgreen** [comment]
The problem come from version of g2o.so,typing the blow command and you will solve it.

cd /usr/local/lib
sudo ln -sv libg2o_csparse_extension.so libg2o_ext_csparse

**Comment by howtocodewang** [comment]
@cumtchenchang You can try this:

cd /usr/local/lib
sudo ln -sv libg2o_csparse_extension.so libg2o_ext_csparse.so

This might be useful!

**Comment by anuragvvworkspace** [comment]
> @cumtchenchang You can try this:
> 
> cd /usr/local/lib
> sudo ln -sv libg2o_csparse_extension.so libg2o_ext_csparse.so
> 
> This might be useful!

This worked for compilation. Thanks

**Comment by ClovesX** [comment]
I also met this problem.After i tried to type the blow command:

cd /usr/local/lib
sudo ln -sv libg2o_csparse_extension.so libg2o_ext_csparse.so

the problem remain.So,how to solve it?Maybe the g2o version is not match?
